In [1]:
%load_ext sql

In [2]:
!service postgresql status

15/main (port 5432): online

In [3]:
%sql postgresql://postgres:postgres_pwd@localhost:5432/practice_db

In [13]:
%config SqlMagic.style = '_DEPRECATED_DEFAULT'  # or 'MSWORD_FRIENDLY', 'RANDOM', 'ORGMODE'

In [14]:
import prettytable
print(prettytable.__dict__.keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__path__', '__file__', '__cached__', '__builtins__', 'annotations', 'Any', '_version', '__version__', 'prettytable', '_DEPRECATED_ALL', '_DEPRECATED_DEFAULT', '_DEPRECATED_DOUBLE_BORDER', '_DEPRECATED_FRAME', '_DEPRECATED_HEADER', '_DEPRECATED_MARKDOWN', '_DEPRECATED_MSWORD_FRIENDLY', '_DEPRECATED_NONE', '_DEPRECATED_ORGMODE', '_DEPRECATED_PLAIN_COLUMNS', '_DEPRECATED_RANDOM', '_DEPRECATED_SINGLE_BORDER', 'HRuleStyle', 'PrettyTable', 'RowType', 'TableHandler', 'TableStyle', 'VRuleStyle', '_warn_deprecation', 'from_csv', 'from_db_cursor', 'from_html', 'from_html_one', 'from_json', '__all__', '__getattr__'])

In [15]:
%%sql
SELECT * FROM enhanced_box_office_data_20_24u LIMIT 10;

 * postgresql://postgres:***@localhost:5432/practice_db
10 rows affected.

[(1, 'Mission: Impossible II', 546388108.0, 215409889.0, 39.4, 330978219.0, 60.6, 2000, 'Adventure, Action, Thriller', '6.126/10', 6741.0, 'en', 'United States of America'),
 (2, 'Gladiator', 460583960.0, 187705427.0, 40.8, 272878533.0, 59.2, 2000, 'Action, Drama, Adventure', '8.217/10', 19032.0, 'en', 'United Kingdom, United States of America'),
 (3, 'Cast Away', 429632142.0, 233632142.0, 54.4, 196000000.0, 45.6, 2000, 'Adventure, Drama', '7.663/10', 11403.0, 'en', 'United States of America'),
 (4, 'What Women Want', 374111707.0, 182811707.0, 48.9, 191300000.0, 51.1, 2000, 'Comedy, Romance', '6.45/10', 3944.0, 'en', 'United Kingdom, United States of America'),
 (5, 'Dinosaur', 349822765.0, 137748063.0, 39.4, 212074702.0, 60.6, 2000, 'Animation, Family, Adventure', '6.544/10', 2530.0, 'en', 'United States of America'),
 (6, 'How the Grinch Stole Christmas', 345842198.0, 260745620.0, 75.4, 85096578.0, 24.6, 2000, 'Family, Comedy, Fantasy', '6.8/10', 7591.0, 'en', 'Germany, United States of America'),
 (7, 'Meet the Parents', 330444045.0, 166244045.0, 50.3, 164200000.0, 49.7, 2000, 'Comedy, Romance', '6.675/10', 5916.0, 'en', 'United States of America'),
 (8, 'The Perfect Storm', 328718434.0, 182618434.0, 55.6, 146100000.0, 44.4, 2000, 'Action, Adventure, Drama, Thriller', '6.466/10', 2312.0, 'en', 'United States of America'),
 (9, 'X-Men', 296339528.0, 157299718.0, 53.1, 139039810.0, 46.9, 2000, 'Adventure, Action, Science Fiction', '7.005/10', 11355.0, 'en', 'United States of America'),
 (10, 'What Lies Beneath', 291420351.0, 155464351.0, 53.3, 135956000.0, 46.7, 2000, 'Drama, Horror, Mystery, Thriller', '6.416/10', 1818.0, 'en', 'United States of America')]

In [30]:
%%sql
SELECT
    *
FROM enhanced_box_office_data_20_24u
WHERE "Year" = 2001
AND "Rating" IS NOT NULL
LIMIT 10;

 * postgresql://postgres:***@localhost:5432/practice_db
10 rows affected.

[(117, 'Tanguy', 24272365.0, 0.0, 0.0, 24272365.0, 100.0, 2001, 'Comedy', '5.964/10', 464.0, 'fr', 'France'),
 (1, "Harry Potter and the Sorcerer's Stone", 974755371.0, 317575550.0, 32.6, 657179821.0, 67.4, 2001, 'Adventure, Fantasy', '7.907/10', 27607.0, 'en', 'United Kingdom, United States of America'),
 (2, 'The Lord of the Rings: The Fellowship of the Ring', 868385360.0, 313364114.0, 36.1, 555021246.0, 63.9, 2001, 'Adventure, Fantasy, Action', '8.4/10', 25348.0, 'en', 'New Zealand, United States of America'),
 (3, 'Monsters, Inc.', 528773250.0, 255873250.0, 48.4, 272900000.0, 51.6, 2001, 'Animation, Comedy, Family', '7.8/10', 18507.0, 'en', 'United States of America'),
 (4, 'Shrek', 484596038.0, 267851831.0, 55.3, 216744207.0, 44.7, 2001, 'Animation, Comedy, Fantasy, Adventure, Family', '7.743/10', 17210.0, 'en', 'United States of America'),
 (5, "Ocean's Eleven", 450717150.0, 183417150.0, 40.7, 267300000.0, 59.3, 2001, 'Thriller, Crime', '7.447/10', 11613.0, 'en', 'United States of America'),
 (6, 'Pearl Harbor', 449220945.0, 198542554.0, 44.2, 250678391.0, 55.8, 2001, 'War, History, Romance, Drama, Action', '6.941/10', 6496.0, 'en', 'United States of America'),
 (7, 'The Mummy Returns', 433013274.0, 202019785.0, 46.7, 230993489.0, 53.3, 2001, 'Adventure, Action, Fantasy', '6.375/10', 7039.0, 'en', 'United States of America'),
 (8, 'Jurassic Park III', 368780809.0, 181171875.0, 49.1, 187608934.0, 50.9, 2001, 'Adventure, Action, Thriller, Science Fiction', '6.1/10', 7133.0, 'en', 'United States of America'),
 (9, 'Planet of the Apes', 362211740.0, 180011740.0, 49.7, 182200000.0, 50.3, 2001, 'Thriller, Science Fiction, Action, Adventure', '5.754/10', 4067.0, 'en', 'United States of America')]

In [23]:
%%sql
SELECT * FROM users_test;

 * postgresql://postgres:***@localhost:5432/practice_db
2 rows affected.

[(1, 'Alice', 'alice@example.com'), (2, 'Bob', 'bob@example.com')]